version: 2

jobs:
  build:
    working_directory: ~/build

    docker:
      - image: jackfirth/racket

    steps:
      - checkout

      - run:
          name: Install gregor
          command: |
            raco pkg install tzdata
            raco pkg install --auto --link ./gregor

      - run:
          name: Run gregor tests
          command: raco test ./gregor-test
